### ISSUE TITLE
Feature request: support classes in SVG output

### ISSUE THREAD

**Issue by stereobooster** [vizdom-dev/vizdom#11]
Graphviz allows to do this

```dot
digraph g {
  a -> b
  a[class="style-me"]
}
```

Class would be in SVG output, so it is possible to style node with CSS.

See https://beoe.stereobooster.com/start-here/styling-with-css/

**Comment by s0l0ist** [comment]
Publishing a new version today with this attribute supported.

**Comment by s0l0ist** [comment]
Waiting on CleverlyDefined harvesting so that I can properly update the latest licenses before releasing. Might take another day.

**Comment by stereobooster** [comment]
Another question. For which items it can be applied?

In graphviz it is:

```
Valid on:
    Edges
    Nodes
    Clusters
    Graphs
```

https://graphviz.org/docs/attrs/class/

Though I only used it for nodes so far

**Comment by s0l0ist** [comment]
All of them :)
