### ISSUE TITLE
Feature request: Vite support

### ISSUE THREAD

**Issue by artem-mangilev** [vizdom-dev/vizdom#14]
Hi! I'm using your library as the layout engine for my Angular library to render nodes. Today, I updated the Angular version, which internally switched from Webpack to Vite. Unfortunately, this caused your library to stop working for me. :(

**Here is an error:**
`"ESM integration proposal for Wasm" is not supported currently. Use vite-plugin-wasm or other community plugins to handle this. Alternatively, you can use '.wasm?init' or '.wasm?url'. See https://vitejs.dev/guide/features.html#webassembly for more details.`

I'm not sure if there's anything you can do on your side to address this issue, but it seems that on my end, I can't modify the internal Vite configuration within Angular.

**Comment by s0l0ist** [comment]
Hi @artem-mangilev check put this issue https://github.com/vizdom-dev/vizdom/issues/9

**Comment by artem-mangilev** [comment]
Yep, found the solution in https://github.com/vizdom-dev/vizdom/issues/9 that works for me, thanks! I'm using `Angular 17.3.12`
