### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by stereobooster** [vizdom-dev/vizdom#9]
Hi 👋 

Some feedback (feel free to discard):

- I can't use package with Vite (Vitest, Astro). I had to do [this change](https://github.com/stereobooster/vizdom-ts) in order to use it
- Some Unicode symbols are not supported, like `label="∅"`
- I created [Rehype plugin for vizdom](https://github.com/stereobooster/beoe/tree/main/packages/rehype-vizdom)

**Comment by s0l0ist** [comment]
Hi @stereobooster, thanks for your feedback!

- Interesting not working in Vite. I was able to get it to work a while back, but I'll circle back to this thread.
- The library uses the NotoSans font so I'm limited by the supported of the glyphs it includes plus working with kerning that the `swash` crate uses. So not all glyphs/unicode can be supported at this time, unfortunately.

**Comment by stereobooster** [comment]
I tried `vite-plugin-wasm`, the problem is that it may work with Vite, but not with Vitest and not with Astro. Similar issue reported here https://github.com/Menci/vite-plugin-wasm/issues/56. 

Which is ok with me - I got my workaround which works so far. Just wanted let you know

**Comment by s0l0ist** [comment]
Now, going to check on Vitest, Astro

**Comment by s0l0ist** [comment]
Ah okay. I'll take a look.

**Comment by s0l0ist** [comment]
Okay, I have an example Vitest + Astro, but you need to use the `node` distribution. There's some issue with the way it works with the `esm` version of the library as you pointed out.

- `npm create astro@latest -- --template with-vitest`
- `npm i @vizdom/vizdom-ts-node`


`basic.test.ts`:
```typescript
import { DirectedGraph } from "@vizdom/vizdom-ts-node";
import { test } from "vitest";
// Edit an assertion and save to see HMR in action

test("Vizdom", () => {
  let graph = new DirectedGraph();
  let v0 = graph.new_vertex({
    render: {
      label: "a",
    },
  });
  let v1 = graph.new_vertex({
    render: {
      label: "b",
    },
  });
  let e0 = graph.new_edge(v0, v1, {
    render: {
      label: `${v0.to_json().render.label} --> ${v1.to_json().render.label}`,
    },
  });
  let positioned = graph.layout();
  let json = positioned.to_json();
  let json_str = json.to_string_pretty();
  console.log(json_str);
});


```

**Comment by stereobooster** [comment]
> There maybe a way to dynamically load a version of the library depending on the runtime, but I'm not aware of a quick solution.

`exports` field in package json maybe? I think one can put `browser` option there, so it would be used for browsers only.

This is general problem. A lot of packages convert binary to Base64 (or Base92, and compress it, and use something like https://github.com/101arrowz/fflate to decompress) and inline string. Which is horrible way to do it, but it is the most portable way.

Anyway. I didn't know about `@vizdom/vizdom-ts-node`. I think it will solve my problem 👍

**Comment by s0l0ist** [comment]
Ah yeah I know exactly what you're talking about with base64ing the WASM and load as a string. I actually tried hard NOT to do it here in this library to not bloat it so much.

BTW here's a test example:

```
// ./src/viz.ts
import { DirectedGraph } from "@vizdom/vizdom-ts-esm";

export function createGraph() {
  const graph = new DirectedGraph();

  const v0 = graph.new_vertex({
    render: {
      label: "a",
    },
  });
  const v1 = graph.new_vertex({
    render: {
      label: "b",
    },
  });

  graph.new_edge(v0, v1, {
    render: {
      label: `${v0.to_json().render.label} --> ${v1.to_json().render.label}`,
    },
  });

  const positioned = graph.layout();
  return positioned.to_json().to_string_pretty();
}
```

Test file:
```
// ./test/basic.test.ts
import { test, vi } from "vitest";

// Mock the ESM version to use the Node.js version in tests
vi.mock("@vizdom/vizdom-ts-esm", async () => {
  return await import("@vizdom/vizdom-ts-node");
});

// In some module, where it uses the `esm` library, the mock should override
// with the node version.
import { createGraph } from "../src/viz";

// Edit an assertion and save to see HMR in action
test("Vizdom", () => {
  let graph = createGraph();
  console.log(graph);
  // do real assertions :) 
});
```

**Comment by s0l0ist** [comment]
@stereobooster, I noticed in your plugin that you're removing the width and height. I can add some methods to optionally add them if needed so you don't have to 'hack' them out.

**Comment by s0l0ist** [comment]
You can now install the latest version (v0.1.12) and no longer need to remove the `width` and `height` attributes. 

If you (or anyone) needs those attributes, you can simply call the appropriate method:

```typescript
const positioned = graph.layout();
const svg = positioned.to_svg().with_width_and_height();
...
```

**Comment by stereobooster** [comment]
> I noticed in your plugin that you're removing the width and height.

motivation behind this: when SVG in-lined, allow to set width and height with CSS, so it would fit container automatically. Something like this:

```css
width: 100%;
height: auto;
```

But it looks weird when graph is very small. I probably need to put some threshold (500px?) before I remove those attributes. This part needs more thought

**Comment by stereobooster** [comment]
A bit more feedback:

- it would be nice to support links, so I can do tricks, like this https://exact.stereobooster.com/ (try hover any node in graph). Now this is generated with GraphViz
- Other idea is to add classes (edge, node) and ids (to edges and node). So one can generate SVG and JSON (on the server) and use a bit of JS (on the client) to highlight edges when hovering a node

**Comment by s0l0ist** [comment]
- Added to my backlog. I think this is relatively easy to do.
 - Also added to backlog.

**Comment by s0l0ist** [comment]
@stereobooster,

In the latest release these are addressed!

For DOT support:
- The DOT attribute for `URL` is now parsed and correctly filled in the SVG for the graph, nodes (also cluster nodes), and edges.
- In the SVG, nodes and edges now have an `id` and `class`
  - `id` has the format `<graph|node|cluster|edge>-<unique_id>` where the `unique_id` is the internal ID that is used.
  - `class` has the format `<graph|node|cluster|edge>`

```dot
digraph {
    URL="https://example1.com"
    a [URL="https://example2.com"]
    a -> b [URL="https://example3.com"]
}
```

The programmatic API also supports the ability to add the `url` parameter as a render attribute:

```typescript
const graph = new DirectedGraph({
  render: {
    url: "https://vizdom.dev",
  }
})
// ...
const v0 = graph.new_vertex({
  render: {
    url: "https://vizdom.dev",
  }
})
// ...
const e0 = graph.new_edge(v0, v1, {
  render: {
    url: "https://vizdom.dev",
  }
})
```

**Comment by stereobooster** [comment]
Thanks for your work.

1. It seems `URL` doesn't work. It can happen though I'm doing something wrong. I will test more
2. For JSON output, for edges is it possible to add `from`, `to` (unique_id of nodes)? Names and form doesn't really matter  - it can be as well tuple (`[from, to]`) or `start`, `end`

**Comment by s0l0ist** [comment]
Okay please let me know what maybe wrong. I tried to emulate what Graphviz does in their SVG format.

For JSON output, yeah that makes sense. I'll add that.

**Comment by s0l0ist** [comment]
Latest release adds `source` (from) and `target` fields on edges in JSON.

**Comment by ThomasAtome** [comment]
Hi !

I have the same problem with Angular and I use the esm plugin

![Capture d’écran 2024-10-18 à 10 51 26](https://github.com/user-attachments/assets/d9048d6d-7cd6-4474-a885-0cf04b98239f)

**Comment by s0l0ist** [comment]
> Hi !
> 
> I have the same problem with Angular and I use the esm plugin
> 
> ![Capture d’écran 2024-10-18 à 10 51 26](https://private-user-images.githubusercontent.com/16318992/377796602-d9048d6d-7cd6-4474-a885-0cf04b98239f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNDI3NDksIm5iZiI6MTcyOTI0MjQ0OSwicGF0aCI6Ii8xNjMxODk5Mi8zNzc3OTY2MDItZDkwNDhkNmQtN2NkNi00NDc0LWE4ODUtMGNmMDRiOTgyMzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDA5MDcyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZTdmMjMzNmM2NmFkNWEwNmM4YTc0OWFhYTcxMWMzODVmODgwNDczYjExYjY4MWU4MjczODBlZDQyZjZiOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QiKGGw6SfDwXcxJZZ25USFgRrEOcm654P8MZam_L_OE)

Hi @ThomasAtome, can provide a minimal reproducible example of what framework(s) you're trying to use so that I can reproduce?

**Comment by s0l0ist** [comment]
@ThomasAtome, 

I've a minimal app that appears to work using Angular 18 **without** SSR (I have not tested using SSR):

- `npm install -g @angular/cli`
- `ng new angular-project`

You'll need to use the `@vizdom/vizdom-ts-web` package, then make changes to `angular.json`:

```json
{
  "projects": {
    "angular-project": {
      "architect": {
        "build": {
          "options": {
            "assets": [
              {
                "glob": "**/*.wasm",
                "input": "node_modules/@vizdom/vizdom-ts-web/"
              }
              
... (add the same to the test config)
        "test": {
          "options": {
            "assets": [
              {
                "glob": "**/*.wasm",
                "input": "node_modules/@vizdom/vizdom-ts-web/"
              }
...
```

```typescript
// src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import init, { DirectedGraph } from '@vizdom/vizdom-ts-web';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent implements OnInit {
  async ngOnInit(): Promise<void> {
    try {
      await init('vizdom_ts_bg.wasm');
      console.log('WebAssembly initialized');
    } catch (error) {
      console.error('Failed to initialize WebAssembly:', error);
    }
  }
  title = 'angular-project';

  create() {
    const graph = new DirectedGraph();
    const v0 = graph.new_vertex({ render: { label: 'hello' } });
    const v1 = graph.new_vertex({ render: { label: 'world' } });
    const _e0 = graph.new_edge(v0, v1, { render: { label: 'a -> b' } });

    const positioned = graph.layout();
    const json = positioned.to_json();
    console.log(json.to_obj());
  }
}

```

**Comment by stereobooster** [comment]
> It seems URL doesn't work (in DOT format). It can happen, though, I'm doing something wrong. I will test more

It didn't work for me, because I use `svgo` to minify svg. And svgo removed `href` from `a`. Theory: `href` needs namespace (according to [spec](https://www.w3.org/wiki/SVG_Links)). I don't have evidence though. I will poke around to find more details

```diff
<svg xmlns="http://www.w3.org/2000/svg" 
+   xmlns:xlink="http://www.w3.org/1999/xlink" 
   version="1.1">
```

**Comment by s0l0ist** [comment]
Should be fixed in the latest release now.

**Comment by stereobooster** [comment]
> I think it's a good idea to include the namespace anyway. It should be fixed in the latest release now.

yes, this solved issue. Now SVGO doesn't remove links

Here is example of client-side interactivity. This is no the most elegant implementation, just to demonstrate the idea. Try hover any node https://beoe.stereobooster.com/examples/vizdom/

**Comment by s0l0ist** [comment]
wow looks cool! Thanks for the awesome demo!

**Comment by s0l0ist** [comment]
This was super valuable. Thank you for your feedback.

New shapes - yes, I need a better way to compute edge-to-shape intersections and be able to center text more idiomatically in any polygon (centroid doesn't always give the best results). One I have those, supporting more shapes will become easier. 

Text search - I do think this is important and have been thinking how to do this in a more performant way. Your suggestion may work! Ideally, I'd use system fonts, but it was a challenge to ensure the bounding box for text labels were the same across all platforms and in the browser (without making calls outside of Wasm to the browser to compute it).
